# Experimentos

## Importando requisitos

In [1]:
import pandas
import os
import numpy
from sklearn.model_selection import GridSearchCV

## Abrindo a planilha

In [2]:
planilha = pandas.read_csv('../Dataset/DataSummary.csv')
planilha

,ID,Type,Name,Train,Test,Class,Length,ED (w=0),DTW (learned_w),DTW (w=100),Default rate,Data donor/editor
0,1,Image,Adiac,390,391,37,176,0.3887,0.3913 (3),0.3964,0.9591,A. Jalba
1,2,Image,ArrowHead,36,175,3,251,0.2000,0.2000 (0),0.2971,0.6057,L. Ye & E. Keogh
2,3,Spectro,Beef,30,30,5,470,0.3333,0.3333 (0),0.3667,0.8000,K. Kemsley & A. Bagnall
3,4,Image,BeetleFly,20,20,2,512,0.2500,0.3000 (7),0.3000,0.5000,J. Hills & A. Bagnall
4,5,Image,BirdChicken,20,20,2,512,0.4500,0.3000 (6),0.2500,0.5000,J. Hills & A. Bagnall
...,...,...,...,...,...,...,...,...,...,...,...,...
123,124,Spectrum,SemgHandMovementCh2,450,450,6,1500,0.6311,0.3622 (1),0.4156,0.8333,C.-C. M. Yeh
124,125,Spectrum,SemgHandSubjectCh2,450,450,5,1500,0.5956,0.2000 (3),0.2733,0.8000,C.-C. M. Yeh
125,126,Sensor,ShakeGestureWiimoteZ,50,50,10,Vary,0.4000,0.1600 (6),0.1400,0.9000,J. Guna
126,127,Simulated,SmoothSubspace,150,150,3,15,0.0933,0.0533 (1),0.1733,0.6667,X. Huang
127,128,Simulated,UMD,36,144,3,150,0.2361,0.0278 (6),0.0069,0.6667,Joseph Fourier University

## Filtrando na planilha os datasets selecionados

In [3]:
planilha = planilha[planilha['ID'].between(97, 128)]
planilha

,ID,Type,Name,Train,Test,Class,Length,ED (w=0),DTW (learned_w),DTW (w=100),Default rate,Data donor/editor
96,97,EOG,EOGVerticalSignal,362,362,12,1250,0.5580,0.5249 (2),0.5525,0.9144,E. Keogh & H. A. Dau
97,98,Spectro,EthanolLevel,504,500,4,1751,0.7260,0.7180 (1),0.7240,0.7480,A. Bagnall
98,99,Sensor,FreezerRegularTrain,150,2850,2,301,0.1951,0.0930 (1),0.1011,0.5000,REFIT project
99,100,Sensor,FreezerSmallTrain,28,2850,2,301,0.3242,0.3242 (0),0.2411,0.5000,REFIT project
100,101,HRM,Fungi,18,186,18,201,0.1774,0.1774 (0),0.1613,0.8978,W. Fonzi
101,102,Trajectory,GestureMidAirD1,208,130,26,Vary,0.4231,0.3615 (5),0.4308,0.9615,H. A. Dau
102,103,Trajectory,GestureMidAirD2,208,130,26,Vary,0.5077,0.4000 (6),0.3923,0.9615,H. A. Dau
103,104,Trajectory,GestureMidAirD3,208,130,26,Vary,0.6538,0.6231 (1),0.6769,0.9615,H. A. Dau
104,105,Sensor,GesturePebbleZ1,132,172,6,Vary,0.2674,0.1744 (2),0.2093,0.8140,I. Maglogiannis
105,106,Sensor,GesturePebbleZ2,146,158,6,Vary,0.3291,0.2215 (6),0.3291,0.8101,I. Maglogiannis
106,107,Motion,GunPointAgeSpan,135,316,2,150,0.1013,0.0348 (3),0.0823,0.4937,A. Ratanamahatana & E. Keogh
107,108,Motion,GunPointMaleVersusFemale,135,316,2,150,0.0253,0.0253 (0),0.0032,0.4747,A. Ratanamahatana & E. Keogh
108,109,Motion,GunPointOldVersusYoung,136,315,2,150,0.0476,0.0349 (4),0.1619,0.4762,A. Ratanamahatana & E. Keogh
109,110,Device,HouseTwenty,40,119,2,2000,0.3361,0.0588 (33),0.0756,0.4202,E. Keogh & S. Gharghabi
110,111,EPG,InsectEPGRegularTrain,62,249,3,601,0.3213,0.1727 (11),0.1285,0.5261,E. Keogh & S. Gharghabi
111,112,EPG,InsectEPGSmallTrain,17,249,3,601,0.3373,0.3052 (1),0.2651,0.5261,E. Keogh & S. Gharghabi
112,113,Traffic,MelbournePedestrian,1194,2439,10,24,0.1525,0.1845 (1),0.2091,0.8995,H.A. Dau
113,114,Image,MixedShapesRegularTrain,500,2425,5,1024,0.1027,0.0911 (4),0.1584,0.7303,E. Keogh
114,115,Image,MixedShapesSmallTrain,100,2425,5,1024,0.1645,0.1674 (7),0.2202,0.7303,E. Keogh
115,116,Sensor,PickupGestureWiimoteZ,50,50,10,Vary,0.4400,0.3400 (17),0.3400,0.9000,J. Guna
116,117,Hemodynamics,PigAirwayPressure,104,208,52,2000,0.9423,0.9038 (1),0.8942,0.9808,M. Guillame-Bert
117,118,Hemodynamics,PigArtPressure,104,208,52,2000,0.8750,0.8029 (1),0.7548,0.9808,M. Guillame-Bert
118,119,Hemodynamics,PigCVP,104,208,52,2000,0.9183,0.8413 (11),0.8462,0.9808,M. Guillame-Bert
119,120,Device,PLAID,537,537,11,Vary,0.4767,0.1657 (12),0.1639,0.8380,P. Schafer
120,121,Power,PowerCons,180,180,2,144,0.0667,0.0778 (3),0.1222,0.5000,"EDF R&D, France"
121,122,Spectrum,Rock,20,50,4,2844,0.1600,0.1600 (0),0.4000,0.5800,Y. Zhu
122,123,Spectrum,SemgHandGenderCh2,300,600,2,1500,0.2383,0.1550 (1),0.1983,0.3500,C.-C. M. Yeh
123,124,Spectrum,SemgHandMovementCh2,450,450,6,1500,0.6311,0.3622 (1),0.4156,0.8333,C.-C. M. Yeh
124,125,Spectrum,SemgHandSubjectCh2,450,450,5,1500,0.5956,0.2000 (3),0.2733,0.8000,C.-C. M. Yeh
125,126,Sensor,ShakeGestureWiimoteZ,50,50,10,Vary,0.4000,0.1600 (6),0.1400,0.9000,J. Guna
126,127,Simulated,SmoothSubspace,150,150,3,15,0.0933,0.0533 (1),0.1733,0.6667,X. Huang
127,128,Simulated,UMD,36,144,3,150,0.2361,0.0278 (6),0.0069,0.6667,Joseph Fourier University

## Realizando experimentos no dataset da primeira linha da tabela

Obtendo o caminho do dataset de exemplo

In [4]:
dataset_exemplo = planilha.iloc[0]['Name']
dataset_exemplo

'EOGVerticalSignal'

In [5]:
dataset_dirname = os.path.join('../Dataset/UCRArchive_2018', dataset_exemplo)
dataset_dirname

'../Dataset/UCRArchive_2018/EOGVerticalSignal'

In [6]:
caminho_arquivo_treino = os.path.join(dataset_dirname, '{}_TRAIN.tsv'.format(dataset_exemplo))
caminho_arquivo_treino

'../Dataset/UCRArchive_2018/EOGVerticalSignal/EOGVerticalSignal_TRAIN.tsv'

In [7]:
caminho_arquivo_teste = os.path.join(dataset_dirname, '{}_TEST.tsv'.format((dataset_exemplo)))
caminho_arquivo_teste

'../Dataset/UCRArchive_2018/EOGVerticalSignal/EOGVerticalSignal_TEST.tsv'

Abrindo datasets

In [8]:
dataset_exemplo_treino = pandas.read_csv(caminho_arquivo_treino, sep='\t', header=None)
dataset_exemplo_treino

,0,1,2,3,4,5,6,7,8,9,...,1241,1242,1243,1244,1245,1246,1247,1248,1249,1250
0,1,-5.70320,-5.89550,-5.88780,-6.08000,-6.17230,-6.26460,-6.2568,-6.1491,-6.4414,...,-113.3100,-113.4100,-113.50000,-114.390000,-114.4800,-113.77000,-113.0700,-113.1600,-112.8500,-112.9400
1,1,-2.18020,-2.30860,-2.33690,-2.36520,-2.39360,-2.02190,-2.0502,-2.0786,-2.5069,...,108.3900,108.5600,108.53000,108.500000,108.4700,108.45000,108.4200,108.3900,108.1600,108.1300
2,1,6.70950,6.52680,6.34420,6.16160,5.97900,5.79640,5.6137,4.5311,2.7485,...,-34.9360,-35.1190,-35.30100,-35.484000,-35.6660,-34.94900,-35.1320,-35.3140,-34.5970,-34.7800
3,1,-0.91251,-0.72238,-0.53226,-0.74213,-0.95201,-1.16190,-1.5718,-1.7816,-1.1915,...,-173.8600,-174.0700,-173.68000,-173.890000,-174.7000,-174.71000,-174.9200,-175.1300,-174.7400,-174.3500
4,1,-5.44400,-5.32610,-4.10820,-3.69020,-3.57230,-3.45440,-3.0364,-2.6185,-2.5006,...,2.0864,1.8044,1.92230,2.040200,2.1582,2.27610,2.3940,2.5119,2.6299,2.7478
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,12,-4.32250,-2.52830,-2.83410,-2.83980,-2.84560,-2.85130,-4.3571,-4.3629,-4.3686,...,-2.1725,-1.3783,-0.08404,-0.089806,1.5044,-0.10134,-1.1071,-1.1129,-1.3186,-1.3244
358,12,-5.91600,-5.90050,-6.68500,-7.76950,-7.75400,-7.73850,-6.6230,-6.6075,-6.5920,...,32.0100,28.3260,25.44100,27.857000,32.0720,32.08800,31.9030,27.9190,27.9340,27.9500
359,12,2.66670,2.60940,2.55220,4.59490,1.63760,0.38033,2.4231,4.0658,2.3085,...,-42.8540,-42.9110,-42.96900,-43.026000,-44.3830,-45.84000,-44.4980,-44.5550,-44.6120,-47.1690
360,12,-1.22680,-1.24790,1.63100,1.50990,1.38880,3.16770,3.0465,2.9254,3.4043,...,-97.5090,-94.3310,-97.75200,-94.573000,-94.6940,-94.81500,-94.9360,-98.0570,-102.5800,-102.7000
361,12,-11.76000,-9.95780,-12.15500,-12.25300,-10.25000,-12.74800,-10.4450,-12.1430,-11.8400,...,-100.6800,-100.7800,-100.07000,-100.170000,-101.0700,-100.37000,-100.4600,-101.3600,-101.4600,-100.7600

In [9]:
dataset_exemplo_teste = pandas.read_csv(caminho_arquivo_teste, sep='\t', header=None)
dataset_exemplo_teste

,0,1,2,3,4,5,6,7,8,9,...,1241,1242,1243,1244,1245,1246,1247,1248,1249,1250
0,1,2.67520,2.68930,3.2034,4.01750,3.93150,3.94560,3.55970,3.87380,3.48790,...,-394.470,-392.450,-391.240,-390.830,-390.710,-390.900,-390.980,-390.870,-390.850,-390.740
1,1,6.84840,6.17140,5.6944,5.31730,5.14030,4.96330,4.18620,3.60920,2.73220,...,-145.670,-144.850,-144.220,-143.900,-143.680,-143.860,-143.530,-144.210,-144.790,-144.960
2,1,-4.91380,-4.87180,-4.8298,-4.98790,-5.14590,-4.50390,-4.66190,-3.72000,-3.57800,...,-169.270,-169.430,-169.590,-169.140,-169.100,-169.260,-169.420,-169.980,-170.730,-170.890
3,1,18.27800,18.29000,18.3020,18.31400,18.32600,19.13800,19.15000,19.86200,19.17400,...,308.330,307.840,308.350,307.670,307.380,308.290,308.300,308.310,307.830,307.840
4,1,-6.26350,-6.28940,-6.0153,-5.34120,-5.46710,-6.09300,-6.71890,-6.34470,-6.47060,...,39.229,38.503,38.077,37.551,37.425,36.499,36.374,37.048,36.922,36.796
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,12,2.02960,1.62900,1.2284,0.92786,0.72729,0.42672,0.42615,0.12558,0.12501,...,-12.375,-14.576,-14.576,-12.577,-12.577,-11.278,-11.279,-12.579,-11.280,-12.580
358,12,1.39790,1.59650,1.6951,0.89369,1.09230,1.29090,0.28948,0.08808,0.28668,...,132.660,132.460,132.660,132.850,133.450,133.950,133.850,134.050,133.850,134.350
359,12,1.90450,1.74240,1.8803,3.41830,2.15620,1.99420,2.13210,3.97010,4.10800,...,93.154,92.992,92.630,92.068,90.606,89.744,89.282,89.020,88.758,88.896
360,12,17.80400,16.97900,16.5540,16.02900,15.70400,15.07800,14.75300,13.22800,11.50300,...,-419.660,-419.990,-420.310,-420.040,-420.060,-420.390,-420.510,-420.840,-421.160,-421.490
361,12,-0.10837,0.44276,1.4939,2.34500,2.29610,2.94730,2.89840,2.84950,2.10070,...,-103.210,-103.860,-103.910,-103.950,-104.300,-104.050,-104.100,-104.450,-104.500,-104.950

### Formatando Dataset

In [10]:
def formatar_dataset(df: pandas.DataFrame) -> pandas.DataFrame:
    """
    Realiza a formatação do dataset.
    :param df: Dataset a ser formatado.
    :return: Dataset formatado.
    """
    classe = df.iloc[:, 0]
    series = df.iloc[:, 1:]

    df_novo = pandas.DataFrame({
        'classe': classe,
        'SérieTemporal': list(series.to_numpy())
    })

    return df_novo

In [11]:
dataset_exemplo_treino = formatar_dataset(dataset_exemplo_treino)
dataset_exemplo_treino

     classe                                      SérieTemporal
0         1  [-5.7032, -5.8955, -5.8878, -6.08, -6.1723, -6...
1         1  [-2.1802, -2.3086, -2.3369, -2.3652, -2.3936, ...
2         1  [6.7095, 6.5268, 6.3442, 6.1616, 5.979, 5.7964...
3         1  [-0.91251, -0.72238, -0.53226, -0.74213, -0.95...
4         1  [-5.444, -5.3261, -4.1082, -3.6902, -3.5723, -...
..      ...                                                ...
357      12  [-4.3225, -2.5283, -2.8341, -2.8398, -2.8456, ...
358      12  [-5.916, -5.9005, -6.685, -7.7695, -7.754, -7....
359      12  [2.6667, 2.6094, 2.5522, 4.5949, 1.6376, 0.380...
360      12  [-1.2268, -1.2479, 1.631, 1.5099, 1.3888, 3.16...
361      12  [-11.76, -9.9578, -12.155, -12.253, -10.25, -1...

[362 rows x 2 columns]

In [12]:
dataset_exemplo_teste = formatar_dataset(dataset_exemplo_teste)
dataset_exemplo_teste

     classe                                      SérieTemporal
0         1  [2.6752, 2.6893, 3.2034, 4.0175, 3.9315, 3.945...
1         1  [6.8484, 6.1714, 5.6944, 5.3173, 5.1403, 4.963...
2         1  [-4.9138, -4.8718, -4.8298, -4.9879, -5.1459, ...
3         1  [18.278, 18.29, 18.302, 18.314, 18.326, 19.138...
4         1  [-6.2635, -6.2894, -6.0153, -5.3412, -5.4671, ...
..      ...                                                ...
357      12  [2.0296, 1.629, 1.2284, 0.92786, 0.72729, 0.42...
358      12  [1.3979, 1.5965, 1.6951, 0.89369, 1.0923, 1.29...
359      12  [1.9045, 1.7424, 1.8803, 3.4183, 2.1562, 1.994...
360      12  [17.804, 16.979, 16.554, 16.029, 15.704, 15.07...
361      12  [-0.10837, 0.44276, 1.4939, 2.345, 2.2961, 2.9...

[362 rows x 2 columns]

### Aplicando algoritmos nos datasets

In [13]:
from app.model.DynamicTimeWarping import DynamicTimeWarping
from app.model.DerivativeDynamicTimeWarping import DerivativeDynamicTimeWarping
from app.model.LongestCommonSubsequence import LongestCommonSubsequence
from app.model.SoftDynamicTimeWarping import SoftDynamicTimeWarping

def aplicar_algoritmos_series_temporais(dataset: pandas.DataFrame, indice_serie_referencia: int = 0) -> pandas.DataFrame:
    """
    Aplica algoritmos às séries temporais.
    :param dataset: Dataset.
    :param indice_serie_referencia: Índice da série temporal de referência.
    :return: Dataset com as distâncias das séries temporais.
    """
    # Instanciando algoritmos
    dtw = DynamicTimeWarping()
    ddtw = DerivativeDynamicTimeWarping()
    lcs = LongestCommonSubsequence()
    soft_dtw = SoftDynamicTimeWarping()

    # Definindo série de referência
    serie_referencia = dataset.iloc[indice_serie_referencia]["SérieTemporal"]

    # Executando algoritmos e adicionando ao Dataset
    print('Executando Dynamic Time Warping')
    dataset['dtw'] = dataset['SérieTemporal'].apply(
        lambda s: dtw.obter_distancia(s, serie_referencia)
    )
    print('Finalizado o Dynamic Time Warping')

    print('Executando o Derivative Dynamic Time Warping')
    dataset['ddtw'] = dataset['SérieTemporal'].apply(
        lambda s: ddtw.obter_distancia(s, serie_referencia)
    )
    print('Finalizado o Derivative Dynamic Time Warping')

    print('Executando o Longest Common Subsequence')
    dataset['lcs'] = dataset['SérieTemporal'].apply(
        lambda s: lcs.lcs(s, serie_referencia)
    )
    print('Finalizado o Longest Common Subsequence')

    print('Executando o Soft Dynamic Time Warping')
    dataset['soft-dtw'] = dataset['SérieTemporal'].apply(
        lambda s: soft_dtw.obter_distancia(s, serie_referencia)
    )
    print('Finalizado o Soft Dynamic Time Warping')

    return dataset

Função auxiliar

In [14]:
import os
import pathlib
import json

def salvar_como_json(dados: object, filepath: str):
    """
    Salva um objeto como JSON.
    :param dados: Objeto a ser salvo
    :param filepath: Caminho do arquivo onde será salvo o objeto.
    :return:
    """

    # Criando o diretório pai, caso ele não exista
    os.makedirs(pathlib.Path(filepath).parent, exist_ok=True)

    with open(filepath, 'w', encoding='utf-8') as arquivo:
        json.dump(dados, arquivo, indent=4, ensure_ascii=False)

In [15]:
def carregar_arquivo_json(filepath: str) -> object:
    """
    Carrega um arquivo JSON.
    :param filepath: Caminho do arquivo onde será lido o objeto.
    :return: Objeto carregado a partir do arquivo JSON.
    """
    with open(filepath, 'r', encoding='utf-8') as arquivo:
        return json.load(arquivo)

In [16]:
dataset_exemplo_treino = aplicar_algoritmos_series_temporais(dataset_exemplo_treino)

Executando Dynamic Time Warping
Finalizado o Dynamic Time Warping
Executando o Derivative Dynamic Time Warping
Finalizado o Derivative Dynamic Time Warping
Executando o Longest Common Subsequence
Finalizado o Longest Common Subsequence
Executando o Soft Dynamic Time Warping
Finalizado o Soft Dynamic Time Warping

In [17]:
dataset_exemplo_teste = aplicar_algoritmos_series_temporais(dataset_exemplo_teste)

Executando Dynamic Time Warping
Finalizado o Dynamic Time Warping
Executando o Derivative Dynamic Time Warping
Finalizado o Derivative Dynamic Time Warping
Executando o Longest Common Subsequence
Finalizado o Longest Common Subsequence
Executando o Soft Dynamic Time Warping
Finalizado o Soft Dynamic Time Warping

Salvando os datasets como Pickle

In [18]:
dataset_exemplo_treino.to_pickle('../Dataset/processed/dataset_exemplo_treino.pkl')
dataset_exemplo_teste.to_pickle('../Dataset/processed/dataset_exemplo_teste.pkl')

### Analisando modelo

Carregando os dados a partir do arquivo Pickle

In [63]:
dataset_exemplo_treino = pandas.read_pickle('../Dataset/processed/dataset_exemplo_treino.pkl')
dataset_exemplo_teste = pandas.read_pickle('../Dataset/processed/dataset_exemplo_teste.pkl')

In [64]:
dataset_exemplo_treino

,classe,SérieTemporal,dtw,ddtw,lcs,soft-dtw
0,1,"[-5.7032, -5.8955, -5.8878, -6.08, -6.1723, -6...",0.000000,0.000000,1250,-1.625967e+03
1,1,"[-2.1802, -2.3086, -2.3369, -2.3652, -2.3936, ...",94123.211165,417.935442,1249,1.490889e+07
2,1,"[6.7095, 6.5268, 6.3442, 6.1616, 5.979, 5.7964...",30054.421325,420.707073,1249,1.901112e+06
3,1,"[-0.91251, -0.72238, -0.53226, -0.74213, -0.95...",14798.394310,481.370766,1249,5.967205e+05
4,1,"[-5.444, -5.3261, -4.1082, -3.6902, -3.5723, -...",65684.048861,471.058642,1249,5.371476e+06
...,...,...,...,...,...,...
357,12,"[-4.3225, -2.5283, -2.8341, -2.8398, -2.8456, ...",50358.440768,1368.307540,1249,4.388884e+06
358,12,"[-5.916, -5.9005, -6.685, -7.7695, -7.754, -7....",66425.290402,1557.679812,1249,7.836528e+06
359,12,"[2.6667, 2.6094, 2.5522, 4.5949, 1.6376, 0.380...",27812.949282,1445.712285,1249,1.841132e+06
360,12,"[-1.2268, -1.2479, 1.631, 1.5099, 1.3888, 3.16...",9598.673229,1463.615157,1249,5.416825e+05
361,12,"[-11.76, -9.9578, -12.155, -12.253, -10.25, -1...",10612.047232,1385.728561,1249,4.874493e+05

In [65]:
dataset_exemplo_teste

,classe,SérieTemporal,dtw,ddtw,lcs,soft-dtw
0,1,"[2.6752, 2.6893, 3.2034, 4.0175, 3.9315, 3.945...",0.000000,0.000000,1250,-1.305859e+03
1,1,"[6.8484, 6.1714, 5.6944, 5.3173, 5.1403, 4.963...",138552.297586,851.164827,1249,3.058980e+07
2,1,"[-4.9138, -4.8718, -4.8298, -4.9879, -5.1459, ...",123473.825114,686.366269,1249,2.502971e+07
3,1,"[18.278, 18.29, 18.302, 18.314, 18.326, 19.138...",388746.788923,1044.108816,1249,2.376134e+08
4,1,"[-6.2635, -6.2894, -6.0153, -5.3412, -5.4671, ...",243547.011488,988.764721,1249,9.044747e+07
...,...,...,...,...,...,...
357,12,"[2.0296, 1.629, 1.2284, 0.92786, 0.72729, 0.42...",214950.506791,1687.177069,1249,7.679610e+07
358,12,"[1.3979, 1.5965, 1.6951, 0.89369, 1.0923, 1.29...",260197.594951,1514.643888,1249,1.175823e+08
359,12,"[1.9045, 1.7424, 1.8803, 3.4183, 2.1562, 1.994...",273938.258348,1601.578512,1249,1.194652e+08
360,12,"[17.804, 16.979, 16.554, 16.029, 15.704, 15.07...",14170.937077,1504.518601,1249,1.302145e+06
361,12,"[-0.10837, 0.44276, 1.4939, 2.345, 2.2961, 2.9...",146724.115359,1435.393663,1249,4.098882e+07

In [66]:
dataset_exemplo_treino['classe'].value_counts()

classe
6     31
7     31
1     30
2     30
3     30
4     30
5     30
8     30
9     30
10    30
11    30
12    30
Name: count, dtype: int64

### Criando conjuntos de teste e treino

Obtendo conjuntos de treino e teste: x e y

In [70]:
def separar_x_y(dataset: pandas.DataFrame) -> tuple[list, list]:
    """
    Separa o conjunto de treino do conjunto de teste
    :param dataset: Dataset de entrada.
    :return: Tupla com os cunjuntos de treino e teste.
    """
    x = (dataset['SérieTemporal'] + dataset['dtw'] + dataset['ddtw'] + dataset['lcs'] + dataset['soft-dtw']).tolist()

    y = dataset['classe'].tolist()

    return x, y

In [71]:
x_train, y_train = separar_x_y(dataset_exemplo_treino)

In [72]:
x_train

[array([-381.66989436, -381.86219436, -381.85449436, ..., -489.12669436,
        -488.81669436, -488.90669436], shape=(1250,)),
 array([15004676.13852603, 15004676.01012603, 15004675.98182603, ...,
        15004786.70872603, 15004786.47872603, 15004786.44872603],
       shape=(1250,)),
 array([1932843.14432783, 1932842.96162783, 1932842.77902783, ...,
        1932801.12082783, 1932801.83782783, 1932801.65482783],
       shape=(1250,)),
 array([613248.32199684, 613248.51212684, 613248.70224684, ...,
        613074.10450684, 613074.49450684, 613074.88450684], shape=(1250,)),
 array([5438874.24168062, 5438874.35958062, 5438875.57748062, ...,
        5438882.19758062, 5438882.31558062, 5438882.43348062],
       shape=(1250,)),
 array([21617097.06453982, 21617097.69753982, 21617098.03053982, ...,
        21617228.90153982, 21617228.63153982, 21617229.17153982],
       shape=(1250,)),
 array([50503489.64387698, 50503490.38187698, 50503490.32087698, ...,
        50502958.97787698, 50502958.21787698, 50502957.75787698],
       shape=(1250,)),
 array([1.80279274e+08, 1.80279276e+08, 1.80279279e+08, ...,
        1.80278391e+08, 1.80278389e+08, 1.80278388e+08], shape=(1250,)),
 array([726181.40903518, 726181.19793518, 726181.18693518, ...,
        726127.26613518, 726127.75513518, 726127.24413518], shape=(1250,)),
 array([10938265.89302381, 10938266.10252381, 10938266.41202381, ...,
        10938331.61292381, 10938331.52192381, 10938331.43192381],
       shape=(1250,)),
 array([537159.2783711, 537153.7128711, 537152.3470711, ...,
        537009.6813711, 537009.2113711, 537008.5513711], shape=(1250,)),
 array([5147073.93451881, 5147073.99131881, 5147073.74801881, ...,
        5147104.67811881, 5147104.73411881, 5147103.89111881],
       shape=(1250,)),
 array([3375350.01450251, 3375349.83302251, 3375348.85155251, ...,
        3375324.71309251, 3375324.73209251, 3375324.65009251],
       shape=(1250,)),
 array([674926.8971576, 674926.8426576, 674926.4880576, ...,
        674826.7729576, 674826.7229576, 674826.6729576], shape=(1250,)),
 array([2845504.28642292, 2845504.40932292, 2845504.43212292, ...,
        2845468.54002292, 2845467.96302292, 2845467.28502292],
       shape=(1250,)),
 array([7829294.43900376, 7829294.50390376, 7829294.56870376, ...,
        7829325.72770376, 7829325.59270376, 7829325.65770376],
       shape=(1250,)),
 array([15190714.18868979, 15190713.98638979, 15190712.28418979, ...,
        15190803.79938979, 15190803.89738979, 15190802.89538979],
       shape=(1250,)),
 array([1240310.15437296, 1240310.13807296, 1240310.12167296, ...,
        1240214.55227296, 1240214.53627296, 1240214.11927296],
       shape=(1250,)),
 array([11001085.67437184, 11001085.76727184, 11001085.16027184, ...,
        11001139.84177184, 11001139.93477184, 11001139.72777184],
       shape=(1250,)),
 array([6330938.40680178, 6330938.43270178, 6330938.45860178, ...,
        6330953.60810178, 6330953.43410178, 6330953.46010178],
       shape=(1250,)),
 array([16170406.75212596, 16170406.54902596, 16170406.34602596, ...,
        16170063.44682596, 16170063.24682596, 16170062.53682596],
       shape=(1250,)),
 array([1866089.53911014, 1866089.85841014, 1866090.27771014, ...,
        1866035.61011014, 1866035.62911014, 1866034.74911014],
       shape=(1250,)),
 array([903975.03199048, 903975.05323048, 903975.07447048, ...,
        903889.71945048, 903889.34045048, 903889.36145048], shape=(1250,)),
 array([746356.78015028, 746356.73735028, 746355.69445028, ...,
        746226.91445028, 746226.87445028, 746227.03445028], shape=(1250,)),
 array([1318906.05513948, 1318905.34523948, 1318905.33523948, ...,
        1318825.87823948, 1318825.86823948, 1318825.85823948],
       shape=(1250,)),
 array([6163035.17150537, 6163034.43648337, 6163033.40148537, ...,
        6163037.39518537, 6163036.76018537, 6163036.82518537],
       shape=(1250,)),
 array([4106182.52858801, 4106182.54138801, 4106182.55418801, ...,
        4106155.51458801, 4106155.52758801, 4106155.54058801],
       shape=(1250,)),
 array([977108.32448442, 977108.29078442, 977108.25718442, ...,
        977007.28748442, 977007.25348442, 977007.22048442], shape=(1250,)),
 array([1682119.40700703, 1682119.15220703, 1682119.29740703, ...,
        1682042.29980703, 1682041.54480703, 1682042.48980703],
       shape=(1250,)),
 array([2519771.01522521, 2519771.05462521, 2519771.09392521, ...,
        2519736.20622521, 2519736.64522521, 2519736.68422521],
       shape=(1250,)),
 array([1686198.53248479, 1686198.54578479, 1686197.55918479, ...,
        1686153.08258479, 1686153.09558479, 1686153.80958479],
       shape=(1250,)),
 array([1036498.17306996, 1036499.47126996, 1036499.46946996, ...,
        1036430.83886996, 1036430.03786996, 1036430.03586996],
       shape=(1250,)),
 array([529880.24378973, 529880.18758973, 529879.93128973, ...,
        529766.18648973, 529767.02648973, 529766.96648973], shape=(1250,)),
 array([500329.12896989, 500328.79735189, 500328.76573189, ...,
        500207.60379189, 500206.77379189, 500205.93379189], shape=(1250,)),
 array([1511116.28317779, 1511116.30467779, 1511116.12607779, ...,
        1511066.44057779, 1511066.16157779, 1511066.18257779],
       shape=(1250,)),
 array([754187.7348822, 754187.7535822, 754186.6722822, ...,
        754107.7555822, 754107.4745822, 754107.4925822], shape=(1250,)),
 array([3024441.22417944, 3024441.25177944, 3024441.27947944, ...,
        3024412.98537944, 3024413.01337944, 3024413.74037944],
       shape=(1250,)),
 array([2544025.98636896, 2544026.02733896, 2544026.76827896, ...,
        2544000.14106896, 2544000.08206896, 2544000.12306896],
       shape=(1250,)),
 array([454291.03524632, 454290.63749632, 454290.63974632, ...,
        454186.84690632, 454186.84690632, 454186.24690632], shape=(1250,)),
 array([1320332.1206783, 1320332.1175783, 1320332.1143783, ...,
        1320278.5357783, 1320278.1327783, 1320278.1297783], shape=(1250,)),
 array([7101953.53041859, 7101953.51631859, 7101954.30221859, ...,
        7101969.65781859, 7101969.64381859, 7101969.62981859],
       shape=(1250,)),
 array([46510445.0812768, 46510445.8617968, 46510445.2422368, ...,
        46510645.6427968, 46510645.7227968, 46510645.8027968],
       shape=(1250,)),
 array([21981720.66034272, 21981720.63374272, 21981720.90704272, ...,
        21981802.93824272, 21981801.81124272, 21981801.48424272],
       shape=(1250,)),
 array([46131077.60361574, 46131076.88051574, 46131077.85731574, ...,
        46131264.53921574, 46131262.70921574, 46131263.08921574],
       shape=(1250,)),
 array([1017575.03708237, 1017575.93588237, 1017575.83468237, ...,
        1017496.50668237, 1017497.40568237, 1017498.50368237],
       shape=(1250,)),
 array([52134504.0411454 , 52134503.73313539, 52134503.8251154 , ...,
        52134717.04106539, 52134718.7410654 , 52134719.2310654 ],
       shape=(1250,)),
 array([29405441.97529038, 29405441.99360038, 29405442.01191038, ...,
        29405569.30201038, 29405569.32201038, 29405567.64201038],
       shape=(1250,)),
 array([8890252.53605387, 8890252.44245386, 8890251.34884387, ...,
        8890283.11302387, 8890283.91902387, 8890284.62502387],
       shape=(1250,)),
 array([23433849.7545014, 23433849.9435014, 23433849.9324014, ...,
        23433958.4808014, 23433958.4708014, 23433958.4608014],
       shape=(1250,)),
 array([13657361.13947917, 13657359.92457917, 13657359.40976917, ...,
        13657417.21207917, 13657416.29707917, 13657416.28207917],
       shape=(1250,)),
 array([2672940.99490419, 2672940.43650419, 2672938.87800419, ...,
        2672913.62760419, 2672914.56860419, 2672914.61060419],
       shape=(1250,)),
 array([973040.75531053, 973040.81241053, 973040.86951053, ...,
        972986.39331053, 972987.45131053, 972987.50831053], shape=(1250,)),
 array([54428.42419602, 54428.44449602, 54428.46479602, ...,
        54325.13039602, 54325.15039602, 54325.37039602], shape=(1250,)),
 array([512571.29424103, 512571.33195103, 512571.36966103, ...,
        512499.01413103, 512499.05213103, 512498.09013103], shape=(1250,)),
 array([279480.73269782, 279481.04249782, 279481.05239782, ...,
        279407.98009782, 279407.99009782, 279408.80009782], shape=(1250,)),
 array([1546734.83391471, 1546734.76581471, 1546734.19783471, ...,
        1546541.41481471, 1546541.35481471, 1546541.28481471],
       shape=(1250,)),
 array([173300.95170145, 173300.14850145, 173299.24540145, ...,
        173164.05050145, 173163.74050145, 173163.74050145], shape=(1250,)),
 array([85264.31849468, 85264.33279468, 85263.14699468, ...,
        85161.94029468, 85161.95429468, 85162.76929468], shape=(1250,)),
 array([2086934.96738227, 2086935.60673227, 2086935.54609227, ...,
        2086738.54245227, 2086738.48245227, 2086738.12245227],
       shape=(1250,)),
 array([2563794.44156694, 2563794.37918794, 2563794.31680794, ...,
        2563582.05055794, 2563581.99055794, 2563581.93055794],
       shape=(1250,)),
 array([9098688.1838908 , 9098687.1244908 , 9098685.6649908 , ...,
        9098720.21829079, 9098720.2592908 , 9098719.9992908 ],
       shape=(1250,)),
 array([5073234.37927172, 5073234.46037172, 5073235.04147172, ...,
        5073244.49247172, 5073245.07357172, 5073245.25467172],
       shape=(1250,)),
 array([8785718.43922801, 8785717.63383401, 8785717.72844201, ...,
        8785762.61445801, 8785762.70945801, 8785762.20445801],
       shape=(1250,)),
 array([4301327.17615538, 4301327.59225538, 4301328.50835538, ...,
        4301334.04595538, 4301334.66195538, 4301334.67805538],
       shape=(1250,)),
 array([2661906.01596274, 2661905.99206274, 2661905.96816274, ...,
        2661875.94966274, 2661875.92566274, 2661875.90166274],
       shape=(1250,)),
 array([4304254.13798398, 4304254.16558397, 4304254.19318397, ...,
        4304245.14738397, 4304247.07498397, 4304247.10258397],
       shape=(1250,)),
 array([19776917.22159381, 19776916.24589381, 19776916.67029381, ...,
        19777019.94289381, 19777020.07289381, 19777020.69289381],
       shape=(1250,)),
 array([6767868.28317869, 6767868.33127869, 6767868.37947869, ...,
        6767902.05157869, 6767902.10057869, 6767901.44857869],
       shape=(1250,)),
 array([318019.63512884, 318019.59322884, 318019.55122884, ...,
        317931.83402884, 317931.79202884, 317931.75002884], shape=(1250,)),
 array([1753315.23844439, 1753315.16024439, 1753315.78204439, ...,
        1753276.54184439, 1753276.46384439, 1753275.28584439],
       shape=(1250,)),
 array([1339750.82211566, 1339750.86621566, 1339750.61031566, ...,
        1339699.39881566, 1339699.44281566, 1339699.48781566],
       shape=(1250,)),
 array([2482698.0486989, 2482697.1929589, 2482696.2371589, ...,
        2482662.7822589, 2482662.8272589, 2482662.8712589], shape=(1250,)),
 array([1390035.78027737, 1390035.69339737, 1390035.60651737, ...,
        1389844.84896737, 1389844.75896737, 1389844.66896737],
       shape=(1250,)),
 array([11427272.28083246, 11427273.16483246, 11427273.24883246, ...,
        11427323.04523246, 11427324.02923246, 11427323.01323246],
       shape=(1250,)),
 array([3133947.86428563, 3133947.72238563, 3133947.68048563, ...,
        3133921.01168563, 3133921.06968563, 3133921.12868563],
       shape=(1250,)),
 array([1.65736327e+08, 1.65736326e+08, 1.65736326e+08, ...,
        1.65735471e+08, 1.65735470e+08, 1.65735469e+08], shape=(1250,)),
 array([2134640.36614062, 2134640.41934062, 2134639.97254062, ...,
        2134570.02124062, 2134570.07424062, 2134569.92824062],
       shape=(1250,)),
 array([5570937.80905124, 5570937.91355124, 5570938.01795124, ...,
        5570953.51565124, 5570954.21965124, 5570954.32465124],
       shape=(1250,)),
 array([5237500.80843667, 5237500.89424667, 5237500.98007667, ...,
        5237508.11647667, 5237508.20227667, 5237507.28807667],
       shape=(1250,)),
 array([9015675.61047334, 9015675.48507334, 9015675.35967334, ...,
        9015401.08947334, 9015400.45947334, 9015400.32947334],
       shape=(1250,)),
 array([2921345.55681009, 2921345.49281009, 2921345.42881009, ...,
        2921300.69541009, 2921300.63141009, 2921299.26741009],
       shape=(1250,)),
 array([9416808.04227198, 9416807.11832198, 9416807.99437198, ...,
        9416841.66807198, 9416841.74407198, 9416842.72007198],
       shape=(1250,)),
 array([5927830.78347436, 5927830.18987436, 5927829.79631436, ...,
        5927824.26571436, 5927825.07211436, 5927825.07851436],
       shape=(1250,)),
 array([9958027.8151209, 9958027.8744409, 9958027.9337709, ...,
        9958052.7930409, 9958052.8520409, 9958052.8120409], shape=(1250,)),
 array([7352902.23162068, 7352902.26042068, 7352902.28932068, ...,
        7352894.40332068, 7352894.43222068, 7352894.96102068],
       shape=(1250,)),
 array([7563842.52141359, 7563842.60251359, 7563842.28371359, ...,
        7563855.90491359, 7563855.48591359, 7563855.06691359],
       shape=(1250,)),
 array([4839719.9646889, 4839718.8267789, 4839718.7888789, ...,
        4839693.4037889, 4839693.3657889, 4839693.3277889], shape=(1250,)),
 array([8263047.80776705, 8263047.88966705, 8263047.97156705, ...,
        8263068.94616705, 8263069.32816705, 8263069.10916705],
       shape=(1250,)),
 array([6522271.21894881, 6522270.84264881, 6522270.86624881, ...,
        6522261.72314881, 6522261.74674881, 6522261.77044881],
       shape=(1250,)),
 array([13467696.14672818, 13467696.24342818, 13467696.34002818, ...,
        13467775.05112818, 13467775.14812818, 13467775.24512818],
       shape=(1250,)),
 array([18041861.14340916, 18041863.43750916, 18041861.53170916, ...,
        18041947.60810916, 18041948.40210916, 18041948.49710916],
       shape=(1250,)),
 array([2434420.79606231, 2434420.85766231, 2434420.71926231, ...,
        2434367.38956231, 2434367.45156231, 2434367.51356231],
       shape=(1250,)),
 array([1745262.73660374, 1745262.75390374, 1745262.07130374, ...,
        1745149.06540374, 1745149.08540374, 1745149.10540374],
       shape=(1250,)),
 array([3848101.34195125, 3848098.98166125, 3848099.02139125, ...,
        3848058.68135125, 3848058.72135125, 3848058.66135125],
       shape=(1250,)),
 array([2381669.5306393, 2381670.6634393, 2381670.3962393, ...,
        2381566.2566393, 2381566.2896393, 2381566.3226393], shape=(1250,)),
 array([2969048.00974398, 2969048.65704398, 2969049.10436398, ...,
        2968955.01074398, 2968954.55774398, 2968954.60474398],
       shape=(1250,)),
 array([14790421.31075988, 14790421.42615988, 14790419.94163988, ...,
        14790511.85995988, 14790511.97495988, 14790512.08995988],
       shape=(1250,)),
 array([2981608.48393089, 2981608.45663089, 2981608.42943089, ...,
        2981470.04393089, 2981470.01393089, 2981469.19393089],
       shape=(1250,)),
 array([3826536.74409586, 3826537.39509586, 3826538.44619586, ...,
        3826487.10709586, 3826487.15809586, 3826486.60909586],
       shape=(1250,)),
 array([3029865.81210209, 3029865.78810209, 3029865.96420209, ...,
        3029767.26070209, 3029767.23670209, 3029767.21270209],
       shape=(1250,)),
 array([30077810.4859031, 30077809.8084031, 30077809.9308031, ...,
        30077978.6642031, 30077979.3842031, 30077979.5142031],
       shape=(1250,)),
 array([13426950.27077354, 13426950.23452353, 13426950.29826353, ...,
        13427022.46510353, 13427022.52910353, 13427022.59310354],
       shape=(1250,)),
 array([1376612.68273585, 1376612.62933585, 1376611.97593585, ...,
        1376528.41153585, 1376528.55853585, 1376528.90553585],
       shape=(1250,)),
 array([10166613.03492859, 10166613.11402859, 10166613.19302859, ...,
        10166653.85762859, 10166653.93662859, 10166654.01562859],
       shape=(1250,)),
 array([592922.04459981, 592922.97659981, 592925.10859981, ...,
        592806.79659981, 592806.22659981, 592805.85659981], shape=(1250,)),
 array([7191052.16555509, 7191052.00860509, 7191051.55164509, ...,
        7191076.74357509, 7191076.88657509, 7191077.02957509],
       shape=(1250,)),
 array([5011357.26182302, 5011357.32302302, 5011357.08422302, ...,
        5011353.68302302, 5011353.74422302, 5011353.80542302],
       shape=(1250,)),
 array([2244761.3480058, 2244761.3447058, 2244761.3415058, ...,
        2244716.7109058, 2244716.7079058, 2244716.7039058], shape=(1250,)),
 array([22222445.1788852, 22222445.3045152, 22222445.4301852, ...,
        22222554.7887852, 22222555.1087852, 22222555.2387852],
       shape=(1250,)),
 array([7978319.05129586, 7978319.07830586, 7978319.90529586, ...,
        7978357.82819586, 7978357.45519586, 7978357.48219586],
       shape=(1250,)),
 array([2736712.22854487, 2736712.30694487, 2736712.08534487, ...,
        2736687.91274487, 2736687.89174487, 2736687.96974487],
       shape=(1250,)),
 array([15710458.46113781, 15710460.58435781, 15710460.70759781, ...,
        15710554.74443781, 15710554.86843781, 15710554.99143781],
       shape=(1250,)),
 array([6516500.52145605, 6516500.51840605, 6516500.51536605, ...,
        6516506.92468605, 6516506.92168605, 6516506.91858605],
       shape=(1250,)),
 array([5863970.64612394, 5863970.62672394, 5863970.20722394, ...,
        5863971.21742394, 5863971.79802394, 5863971.77862394],
       shape=(1250,)),
 array([2104432.35203531, 2104432.30385531, 2104432.25566531, ...,
        2104379.47007531, 2104379.42207531, 2104379.37407531],
       shape=(1250,)),
 array([7063976.67675889, 7063976.70705889, 7063976.33725889, ...,
        7063977.26275889, 7063977.29305889, 7063977.32325889],
       shape=(1250,)),
 array([1029842.23020927, 1029842.20760927, 1029842.18500927, ...,
        1029751.17920927, 1029752.45620927, 1029752.43420927],
       shape=(1250,)),
 array([4210204.75912759, 4210204.77862759, 4210204.79812759, ...,
        4210176.04592759, 4210176.06492759, 4210175.38492759],
       shape=(1250,)),
 array([1056181.36839589, 1056181.49739589, 1056181.52639589, ...,
        1056132.19839589, 1056132.22739589, 1056132.25639589],
       shape=(1250,)),
 array([10832115.26127172, 10832116.57993172, 10832115.29858172, ...,
        10832165.12335172, 10832165.14235172, 10832165.16035172],
       shape=(1250,)),
 array([1769633.3705964, 1769633.4162964, 1769633.5620964, ...,
        1769603.3970964, 1769604.0430964, 1769604.0880964], shape=(1250,)),
 array([856965.64820715, 856965.66320715, 856965.67920715, ...,
        856918.84720715, 856918.56320715, 856918.57920715], shape=(1250,)),
 array([1721127.83733891, 1721124.44653891, 1721124.05583891, ...,
        1721077.37853891, 1721077.38753891, 1721077.39653891],
       shape=(1250,)),
 array([2824608.58248875, 2824608.63348875, 2824613.28458875, ...,
        2824592.24728875, 2824592.29828875, 2824592.34928875],
       shape=(1250,)),
 array([186860.16103081, 186860.90336081, 186860.94569081, ...,
        186772.34387081, 186772.28687081, 186772.32887081], shape=(1250,)),
 array([947950.1564594, 947950.1651594, 947950.1737594, ...,
        947893.9392594, 947893.9482594, 947896.6572594], shape=(1250,)),
 array([409350.93335736, 409350.94415736, 409350.95485736, ...,
        409272.28155736, 409274.09155736, 409272.90255736], shape=(1250,)),
 array([10132045.74305263, 10132045.87705263, 10132046.01205263, ...,
        10132092.14305263, 10132092.27705263, 10132089.51205263],
       shape=(1250,)),
 array([9684102.14732657, 9684102.54202657, 9684102.63682657, ...,
        9684171.02512657, 9684172.52012657, 9684171.21512657],
       shape=(1250,)),
 array([530252.82497507, 530252.79037507, 530252.75567507, ...,
        530188.42227507, 530188.38727507, 530188.35327507], shape=(1250,)),
 array([790855.77841331, 790856.79541331, 790860.01241331, ...,
        790778.91541331, 790778.93241331, 790778.94941331], shape=(1250,)),
 array([1911702.97759213, 1911702.95839213, 1911702.93919213, ...,
        1911596.22219213, 1911596.20219213, 1911596.18219213],
       shape=(1250,)),
 array([3373426.66978752, 3373426.60378752, 3373426.53788752, ...,
        3373207.28198752, 3373207.21198752, 3373206.85198752],
       shape=(1250,)),

In [73]:
y_train

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12]

In [74]:
x_test, y_test = separar_x_y(dataset_exemplo_teste)

### Treinando modelo

Normalizando os dados

In [75]:
from sklearn.preprocessing import StandardScaler

In [76]:
scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

Criando e treinando modelo KNeighbors

In [77]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV

In [87]:
parametros = {'n_neighbors': [1, 3, 5, 7, 9, 11]}
knn = KNeighborsClassifier()
grid = GridSearchCV(knn, parametros, cv=5)
grid.fit(x_train, y_train)
knn.fit(x_train, y_train)

KNeighborsClassifier()

Realizando predições

In [88]:
y_pred = knn.predict(x_test)
y_pred

array([ 6,  6,  6,  1,  4,  5,  4,  1,  3,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  5,  5,  6,  6,  6,  6,  6,  6,  6,  6,  6,  5,  5,  6,  6,  6,
        6,  6,  6,  5,  6,  6,  1,  1,  5,  1,  1,  1,  1,  1,  1,  5,  6,
        5,  5,  6,  5,  5,  5,  6,  5,  6,  4,  6,  5,  5,  4,  6,  5,  5,
        5,  5,  6,  6,  6,  5,  6,  6,  4,  5,  2,  5,  6,  5,  5,  5,  4,
        4,  3,  5,  5,  4,  4,  6,  6,  6,  3,  6,  6,  6,  5,  5,  5,  6,
        6,  6,  6,  3,  6,  5,  5,  5,  2,  5,  5,  4,  5,  5,  4,  5,  2,
        4,  5,  6,  1,  1,  1,  5,  6,  5,  1,  6,  1,  5,  5,  7,  5,  6,
       11,  6,  6,  6,  6,  5,  4,  6,  9,  5,  6,  6,  5,  6,  1,  4,  6,
        6,  5,  5,  6,  6,  6,  6,  6,  1,  1,  2,  1,  1,  1,  1,  4,  5,
        3,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  5,  9,  5,  5,  5,  5,
        6,  6,  1,  3,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  5,  5,
        4,  5,  5,  3,  2,  6,  6,  4,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  2,  6,  5,  5,  6,  9,  6,  6,  2,  5,  5,  3,  5,  5,  2,
        5,  4,  7,  2,  4,  5,  5,  4,  5,  1,  5,  5,  3,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  1,  6,  1,  6,  6,  6,  4,  1,  1,  5,  1,  1,  1,  1,
        1,  1,  1,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  1,  5,  5,
        5,  6,  5,  5,  5,  4,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  2,
        5,  3,  3,  5,  5,  5,  5,  6,  5,  6,  6,  6,  6,  1,  6,  6,  6,
        6,  6,  2,  6,  4,  9,  2,  3,  7,  4,  6,  6,  5,  5,  4,  6,  2,
        5,  5,  5,  6,  6])

Avaliando modelo

In [89]:
from sklearn.metrics import accuracy_score

In [90]:
acuracia = accuracy_score(y_test, y_pred)
acuracia

0.10220994475138122

Criando e treinando modelo SVM

In [92]:
import sklearn.svm

In [94]:
svm = sklearn.svm.SVC()
svm.fit(x_train, y_train)

SVC()

Realizando predições

In [96]:
y_pred = svm.predict(x_test)
y_pred

array([6, 6, 6, 1, 5, 5, 5, 1, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 5, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 5, 5, 6, 6, 6, 6, 6, 6, 5, 6, 6, 1, 1, 5, 5,
       5, 1, 5, 5, 1, 5, 6, 5, 5, 6, 5, 5, 5, 6, 7, 6, 5, 6, 5, 5, 5, 6,
       5, 5, 7, 5, 6, 6, 6, 7, 6, 6, 5, 5, 6, 5, 6, 5, 7, 5, 5, 5, 5, 5,
       5, 5, 5, 6, 6, 6, 5, 6, 6, 6, 5, 5, 7, 6, 6, 6, 6, 5, 6, 7, 5, 5,
       7, 5, 5, 5, 5, 5, 5, 7, 7, 5, 5, 6, 1, 5, 1, 5, 6, 5, 6, 6, 1, 7,
       5, 6, 5, 6, 6, 6, 6, 6, 6, 5, 5, 6, 7, 5, 6, 6, 5, 6, 5, 5, 6, 6,
       5, 7, 6, 6, 6, 6, 6, 1, 1, 6, 1, 1, 5, 1, 5, 5, 5, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 5, 6, 5, 5, 5, 7, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 5, 7, 5, 5, 7, 5, 7, 6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 5, 5, 6, 7, 6, 6, 7, 5, 5, 5, 5, 7, 6, 5, 5, 6, 7,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 1, 5, 5,
       1, 5, 5, 1, 5, 1, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 5, 5, 6,
       5, 5, 7, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5,
       6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 6, 5, 6, 7, 5, 6, 6, 6, 6,
       5, 5, 5, 6, 7, 5, 5, 5, 6, 6])

Avaliando modelo

In [97]:
acuracia = accuracy_score(y_test, y_pred)
acuracia

0.13812154696132597